apiVersion: v1
kind: ConfigMap
metadata:
  name: bookmarker-config
data:
  postgres_host: postgres-service
  postgres_port: "5432"
  postgres_dbname: bookmarkdb
---

apiVersion: v1
kind: Secret
metadata:
  name: bookmarker-secret
data:
  postgres_username: cG9zdGdyZXM=
  postgres_password: cG9zdGdyZXM=
type: Opaque



